pipeline:
  build:
    image: node:latest
    commands: npm install
  test:
    image: node:latest
    commands: npm run test
steps:
- name: publish  
  image: plugins/ecr
  settings:
    repo: 67794846884.dkr.ecr.us-east-1.amazonaws.com/hash-brown
    registry: 67794846884.dkr.ecr.us-east-1.amazonaws.com
    dockerfile: /home/madhurkatyal/Dotnet-Core-Projects/hashbrown-cms



    
  
