pipeline:
  build:
    image: node:latest
    commands: npm install
  test:
    image: node:latest
    commands: npm run test
  services:
    - name: database
      image: mongo:latest
      ports:
      - 27017



    
  